"""empty message

Revision ID: 623595951e7f
Revises: 92fb603efb23
Create Date: 2022-11-14 19:35:24.208791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '623595951e7f'
down_revision = '92fb603efb23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('complete', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'complete')
    # ### end Alembic commands ###
